In [1]:
import pandas as pd
from df_datefixer.fixer import fix_dates

In [2]:
df = pd.DataFrame({
    'start_date': ['2022-01-01', '1/2/2022', 'bad-date', None],
    'end_date': ['2022-02-01', 'invalid', '03-03-2022', None]
})

df.head()

   start_date    end_date
0  2022-01-01  2022-02-01
1    1/2/2022     invalid
2    bad-date  03-03-2022
3        None        None

In [3]:
df_2 = pd.read_csv("test_dataset.csv", delimiter=";")

In [4]:
# test basic single-column usage
fixed_df = fix_dates(df, column="start_date", target_format="%d/%m/%Y")
fixed_df

! 2 problematic date values found in column "start_date":
- Row 2: bad-date
- Row 3: None (missing)

   start_date    end_date
0  01/01/2022  2022-02-01
1  02/01/2022     invalid
2           0  03-03-2022
3           0        None

In [5]:
# test basic single-column usage
fixed_df2 = fix_dates(df_2, column="Date", target_format="%Y")
fixed_df2

! 1 problematic date values found in column "Date":
- Row 15: 12-Sept-19945

    Date          ID
0   1975      123456
1   1755       98765
2   1899     3472549
3   2035     8473940
4   1975       55555
5   1975    94739002
6   1975  2411430027
7   2024      345666
8   2025        3212
9   1975           1
10  1975     9800000
11  1975   777777456
12  1975        4442
13  1975          23
14  1975    87907363
15     0       98999
16  2015        3456
17  1975        4567
18  1999         123
19  2001     2332492
20  1975    98776101

In [6]:
# test multi-column fixing
fixed_df_multi = fix_dates(df, columns=['start_date', 'end_date'], target_format="%Y")
fixed_df_multi

! 2 problematic date values found in column "start_date":
- Row 2: bad-date
- Row 3: None (missing)
! 2 problematic date values found in column "end_date":
- Row 1: invalid
- Row 3: None (missing)

  start_date end_date
0       2022     2022
1       2022        0
2          0     2022
3          0        0

In [7]:
# test conversion to datetime
fixed_datetime = fix_dates(df, columns=['start_date', 'end_date'], convert_to_datetime=True)
print(fixed_datetime.dtypes)
fixed_datetime

! 2 problematic date values found in column "start_date":
- Row 2: bad-date
- Row 3: None (missing)
! 2 problematic date values found in column "end_date":
- Row 1: invalid
- Row 3: None (missing)
start_date    object
end_date      object
dtype: object

            start_date             end_date
0  2022-01-01 00:00:00  2022-02-01 00:00:00
1  2022-01-02 00:00:00                    0
2                    0  2022-03-03 00:00:00
3                    0                    0

In [8]:
# test custom placeholder
fixed_custom_placeholder = fix_dates(df, columns=['start_date', 'end_date'], missing_value="missing_date")
fixed_custom_placeholder

! 2 problematic date values found in column "start_date":
- Row 2: bad-date
- Row 3: None (missing)
! 2 problematic date values found in column "end_date":
- Row 1: invalid
- Row 3: None (missing)

     start_date      end_date
0    2022-01-01    2022-02-01
1    2022-01-02  missing_date
2  missing_date    2022-03-03
3  missing_date  missing_date

In [9]:
# test inplace modification
df_copy = df.copy()
fix_dates(df_copy, columns=['start_date'], inplace=True)
df_copy

! 2 problematic date values found in column "start_date":
- Row 2: bad-date
- Row 3: None (missing)

   start_date    end_date
0  2022-01-01  2022-02-01
1  2022-01-02     invalid
2           0  03-03-2022
3           0        None

In [10]:
# test empty DataFrame
empty_df = pd.DataFrame({'dates': []})
fixed_empty = fix_dates(empty_df, column="dates")
fixed_empty

Empty DataFrame
Columns: [dates]
Index: []